### ISSUE TITLE
Any schema with a `domain` attribute fails to save.

### ISSUE THREAD

**Issue by jaredhanson** [LearnBoost/mongoose#1338]
If I define a Schema with a `domain` property, and then attempt to save a model instance, it  fails with the following error:

```
events.js:84
        this.domain.enter();
                    ^
TypeError: Object github.com has no method 'enter'
    at model.EventEmitter.emit (events.js:84:21)
    at model.save (/Users/jaredhanson/Projects/website/node_modules/mongoose/lib/model.js:383:10)
    at model.module.exports.hook.proto.(anonymous function)._done (/Users/jaredhanson/Projects/website/node_modules/mongoose/node_modules/hooks/hooks.js:59:24)
    at module.exports.hook.proto.(anonymous function)._next (/Users/jaredhanson/Projects/website/node_modules/mongoose/node_modules/hooks/hooks.js:52:28)
    at fnWrapper (/Users/jaredhanson/Projects/website/node_modules/mongoose/node_modules/hooks/hooks.js:159:8)
    at model.module.exports (/Users/jaredhanson/Projects/node/mongoose-timestamps/lib/timestamps.js:22:5)
    at module.exports.hook.proto.(anonymous function)._next (/Users/jaredhanson/Projects/website/node_modules/mongoose/node_modules/hooks/hooks.js:50:30)
    at fnWrapper (/Users/jaredhanson/Projects/website/node_modules/mongoose/node_modules/hooks/hooks.js:159:8)
    at complete (/Users/jaredhanson/Projects/website/node_modules/mongoose/lib/document.js:920:5)
    at Document.validate.err (/Users/jaredhanson/Projects/website/node_modules/mongoose/lib/document.js:911:20)
```

In this case, "github.com" is the value I assigned to the `domain` property with a schema that looks like:

```
var AccountSchema = new Schema({
    userId      : { type: Schema.ObjectId, required: true }
  , domain      : String
  , uid         : String
  , username    : String
  , displayName : String
  , name: {
      familyName : String
    , givenName  : String
    , middleName : String
  }
  , credentials : [ CredentialSchema ]
});
````

Note, this is actually a conflict with Node core, which has a colliding `domain` property with anything that inherits from `EventEmitter`.  I have a running discussion with @isaacs about it here:

https://github.com/joyent/node/issues/3922

It may help to get more input from Mongoose developers.

**Comment by vkarpov15** [comment]
Not an issue in 4.0 anymore, since Document no longer inherits from EventEmitter to avoid this particular mess. See #1451.

As a side note, I really hope ES7 provides better control over encapsulation and domains go away before Node 1.0.
