### ISSUE TITLE
Upgrade mongodb driver to the latest

### ISSUE THREAD

**Issue by inetfuture** [LearnBoost/mongoose#2012]
mongodb 2.6 has been released, after upgrading it, I run into some key check errors, which disappeared after using the latest mongodb driver(https://github.com/mongodb/node-mongodb-native/blob/1.4/HISTORY#L9-L12)

For example:

```js
App = mongoose.model 'App'
App.remove({
  name: {
    $not: { $in: 'aaron' }
  }
})
```

will cause
```
key $not must not start with '$'
  at Error (<anonymous>:null:null)
  at Function.checkKey (/root/wp/server/node_modules/mongoose/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:1442:13)
  at serializeObject (/root/wp/server/node_modules/mongoose/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:356:14)
  at packElement (/root/wp/server/node_modules/mongoose/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:855:23)
  at serializeObject (/root/wp/server/node_modules/mongoose/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:360:15)
  at packElement (/root/wp/server/node_modules/mongoose/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:855:23)
  at serializeObject (/root/wp/server/node_modules/mongoose/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:360:15)
  at packElement (/root/wp/server/node_modules/mongoose/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:855:23)
  at serializeObject (/root/wp/server/node_modules/mongoose/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:343:15)
  at packElement (/root/wp/server/node_modules/mongoose/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:855:23)
  at serializeObject (/root/wp/server/node_modules/mongoose/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:360:15)
  at Function.serializeWithBufferAndIndex (/root/wp/server/node_modules/mongoose/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:332:10)
  at BSON.serializeWithBufferAndIndex (/root/wp/server/node_modules/mongoose/node_modules/mongodb/node_modules/bson/lib/bson/bson.js:1526:15)
  at [object Object].QueryCommand.toBinary (/root/wp/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/commands/query_command.js:223:35)
  at [object Object].Connection.write (/root/wp/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection.js:243:37)
  at __executeQueryCommand (/root/wp/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1657:16)
  at Db._executeQueryCommand (/root/wp/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1805:7)
  at Db.command (/root/wp/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1094:8)
  at removeWithWriteCommands (/root/wp/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:296:11)
  at Collection.remove (/root/wp/server/node_modules/mongoose/node_modules/mongodb/lib/mongodb/collection/core.js:337:12)
  at NativeCollection.(anonymous function) [as remove] (/root/wp/server/node_modules/mongoose/lib/drivers/node-mongodb-native/collection.js:129:28)
```

Similar error when key contains dots: `key info.name must not contain \'.\'`

**Comment by Koka5** [comment]
i am still trapped in this issue.  my configs are : 
nodejs : 0.10
mongodb : 2.6.8 (no issues with 2.4.x)
mongodb driver (npm package version) : 2.1.3 (have tried with 1.4.x and 1.3.x, but error is still there, even emptying node_modules and again `npm install`)

I am doing following query

  coll.remove({ _id : { '$ne' :  SomeId }, blah : blaVal });
But that gives the error : key $ne must not start with '$'

I have started facing this issue, when i migrated mongodb 2.4 to 2.6

**Comment by vkarpov15** [comment]
@Koka5 are you using mongoose at all, or are you just using the node driver directly?

**Comment by Koka5** [comment]
Yes i am using mongoose as well,.

**Comment by vkarpov15** [comment]
The following script works fine for me. Try tweaking it to see if you can reproduce your issue.

```javascript
'use strict';

var assert = require('assert');
var mongodb = require('mongodb');

mongodb.MongoClient.connect('mongodb://localhost:27017/test', function(err, db) {
  assert.ifError(err);
  db.collection('test').remove({ _id: { $ne: 1 }, test: 'blah' }, function(err) {
    assert.ifError(err);
    process.exit(0);
  });
});
```

Also, for future reference, this GitHub is for mongoose issues - please report driver issues on the [mongodb node driver JIRA](https://jira.mongodb.org/browse/NODE/?selectedTab=com.atlassian.jira.jira-projects-plugin:summary-panel)
