### ISSUE TITLE
'undefined is not a function' when I count with promises 

### ISSUE THREAD

**Issue by andronat** [LearnBoost/mongoose#2204]
Hi, I am getting this error:

```
TypeError: undefined is not a function
    at Query.count (/vagrant/shifterproject/node_modules/mongoose/lib/query.js:1205:5)
    at Function.count (/vagrant/shifterproject/node_modules/mongoose/lib/model.js:1072:13)
    at Object.exports.counters [as handle] (/vagrant/shifterproject/app/controllers/api.server.controller.js:36:12)
    at next_layer (/vagrant/shifterproject/node_modules/express/lib/router/route.js:103:13)
    at Route.dispatch (/vagrant/shifterproject/node_modules/express/lib/router/route.js:107:5)
    at /vagrant/shifterproject/node_modules/express/lib/router/index.js:205:24
    at Function.proto.process_params (/vagrant/shifterproject/node_modules/express/lib/router/index.js:269:12)
    at next (/vagrant/shifterproject/node_modules/express/lib/router/index.js:199:19)
    at Layer.favicon [as handle] (/vagrant/shifterproject/node_modules/serve-favicon/index.js:54:44)
    at trim_prefix (/vagrant/shifterproject/node_modules/express/lib/router/index.js:240:15)
```

when I run this:

```Server.count({error: {$eq:''}}).exec()```

I am using the promise interface and my actual code is like this:

```
when.all([
    Server.count({queued:true}).exec(),
    Server.count({error: {$eq:''}}).exec()
  ])
  .spread(sendResponse)
  .otherwise(function(err) {
    res.send(400, String(err));
  });
```

I added a ```console.log()``` in ```/vagrant/shifterproject/node_modules/mongoose/lib/query.js:1205``` in the ```catch``` section and I discovered that:

```
[Error: Can't use $eq with String.]
``` 

So, the problem was that there was no callback! Shouldn't promises take care of that? I am new to javascript and I am not sure if this is a bug or I did something wrong :/

P.S. I am using mongodb 2.6, and in command-line I can search with ```$eq``` shouldn't be that available also in mongoose?

Thanks!

**Comment by dbellavista** [comment]
I'm having this problem as well. The documentation says that count can be called without the callback, however when the conditions raise an error, the callback is called even if it isn't present.
https://github.com/LearnBoost/mongoose/blob/3.8.21/lib/query.js#L1205

The expected behavior should raise the error in the final callback or promise.

**Comment by dbellavista** [comment]
8ebf67e the if clause misses a parentheses

**Comment by vkarpov15** [comment]
Fixed in the next commit. Thanks for pointing that out though :)
