### ISSUE TITLE
Node debugger crashes with 3.9

### ISSUE THREAD

**Issue by rtm** [LearnBoost/mongoose#2597]
I am using mongoose 3.9 with node 0.11.13. The node debugger crashes. Is this a mongo problem or a mongoose problem?

    Debugger listening on port 5858
    { [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
    js-bson: Failed to load c++ bson extension, using pure JS version

    ##############################################################
    #
    #   !!! MONGOOSE WARNING !!!
    #
    #   This is an UNSTABLE release of Mongoose.
    #   Unstable releases are available for preview/testing only.
    #   DO NOT run this in production.
    #
    ##############################################################

    ~/project\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\base.js:246
    throw message;
    ^
    TypeError: Cannot read property '1' of null
    at getCallerFuncLocation (eval at WRAPPED_BY_NODE_INSPECTOR (~bob\npm\node_modules\node-inspector\node_modules\v8-debug\v8-debug.js:86:15), <anonymous>:63:31)
    at new ConsoleMessage (eval at WRAPPED_BY_NODE_INSPECTOR (~bob\npm\node_modules\node-inspector\node_modules\v8-debug\v8-debug.js:86:15), <anonymous>:10:20)
    at Console.eval [as log] (eval at WRAPPED_BY_NODE_INSPECTOR (~bob\npm\node_modules\node-inspector\node_modules\v8-debug\v8-debug.js:86:15), <anonymous>:103:21)
    at ~/project\src\utils\mongoose.js:13:13
    at open (~/project\node_modules\mongoose\lib\connection.js:484:17)
    at Db.authenticate._callback (~/project\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:703:5)
    at ~/project\node_modules\mongoose\node_modules\mongodb\lib\mongodb\auth\mongodb_cr.js:65:13
    at ~/project\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1157:7
    at ~/project\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:1890:9
    at Server.Base._callHandler (~/project\node_modules\mongoose\node_modules\mongodb\lib\mongodb\connection\base.js:448:41)

**Comment by vkarpov15** [comment]
I don't have much experience using node inspector, so I'm not sure off the top of my head. The error itself looks like its in mongoose, but always tricky to figure out since debuggers do a lot of weird magic. Can you tell me the exact version of mongoose? Also, does it work fine without node inspector?

**Comment by rtm** [comment]
Mongoose version is 3.9.7. Yes, it works fine without node inspector.

**Comment by ilanbiala** [comment]
@rtm what about 4.0.0-rc1, does that crash node-inspector?

**Comment by vkarpov15** [comment]
So the following node script:

```javascript
var mongoose = require('mongoose');

mongoose.connect('mongodb://localhost:27017');

var childSchema = new mongoose.Schema({ name: { type: Number, validate: function(v) { return false; } } });

var Child = mongoose.model('Child', childSchema);

var y = new Child;

y.save(function(err) {
  console.log('Error: ' + err);
});
```

works fine for me with node-inspector on node 0.11.13:

```
~/Workspace/10gen/troubleshoot-mongoose $ ./node_modules/node-inspector/bin/node-debug.js test.js
Node Inspector is now available from http://127.0.0.1:8080/debug?port=5858
Debugging `test.js`

Debugger listening on port 5858
GET / HTTP/1.1: (no value)
User-Agent: curl/7.35.0
Host: localhost:5858
Accept: */*

##############################################################
#
#   !!! MONGOOSE WARNING !!!
#
#   This is an UNSTABLE release of Mongoose.
#   Unstable releases are available for preview/testing only.
#   DO NOT run this in production.
#
##############################################################

Error: null
^C
```

Looking at your stack trace, the error looks like its triggered in the callback to `connection.open()`:

```
TypeError: Cannot read property '1' of null
at getCallerFuncLocation (eval at WRAPPED_BY_NODE_INSPECTOR (~bob\npm\node_modules\node-inspector\node_modules\v8-debug\v8-debug.js:86:15), <anonymous>:63:31)
at new ConsoleMessage (eval at WRAPPED_BY_NODE_INSPECTOR (~bob\npm\node_modules\node-inspector\node_modules\v8-debug\v8-debug.js:86:15), <anonymous>:10:20)
at Console.eval [as log] (eval at WRAPPED_BY_NODE_INSPECTOR (~bob\npm\node_modules\node-inspector\node_modules\v8-debug\v8-debug.js:86:15), <anonymous>:103:21)
at ~/project\src\utils\mongoose.js:13:13 // <------ application
at open (~/project\node_modules\mongoose\lib\connection.js:484:17) // <---- mongoose calls back to application
at Db.authenticate._callback (~/project\node_modules\mongoose\node_modules\mongodb\lib\mongodb\db.js:703:5)
at ~/project\node_modules\mongoose\node_modules\mongodb\lib\mongodb\auth\mongodb_cr.js:65:13
```

Can you tell me what the code around "src/utils/mongoose.js:13" is doing?

**Comment by vkarpov15** [comment]
Can't repro, looks like error in application code, and node 0.11.13 is finally obsolete. I'm going to close this - reopen if it's still an issue.

**Comment by rtm** [comment]
Many thanks for looking at this, works now.
