### ISSUE TITLE
useDb memory leak warnings

### ISSUE THREAD

**Issue by vkarpov15** [LearnBoost/mongoose#2636]
Seeing these errors for uses of .useDb(). 

Connecting to mongo: 192.168.59.103:27017(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace: 
  at [object Object].addListener (events.js:164:15)
  at [object Object].once (events.js:189:8)
  at new Db (/Users/bkaplan/si/vi-security-subjects/node_modules/mongodb/lib/db.js:163:12)
  at [object Object].Db.db (/Users/bkaplan/si/vi-security-subjects/node_modules/mongodb/lib/db.js:772:12)
  at wireup (/Users/bkaplan/si/vi-security-subjects/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:110:26)

Its not clear (to me) whether this is a real leak or due to the connection pooling.

**Comment by vkarpov15** [comment]
Same issue as #2073 - may be improved at some point but for now its expected behavior
