### ISSUE TITLE
findOne method retrieves document with missing _id leading to an CastError when save() is called

### ISSUE THREAD

**Issue by Zonic** [LearnBoost/mongoose#2646]
I'm currently on a very weird mongoose error and I don't know what is causing this problem. When I call `findOne` method, I get a valid instance, with only the `_id` field not initialized. When I'm trying to save the changes in that document it crashes with 

    { [CastError: Cast to ObjectId failed for value "[object Object]" at path "_id"]
     message: 'Cast to ObjectId failed for value "[object Object]" at path "_id"',
     name: 'CastError',
     type: 'ObjectId',
     value: 
       { from_node_id: 52e10f6acce9daa7f3bf3162,
         target_id: 'a' },
     path: '_id' }

I have a simple Schema Definition:

    var mongoose = require('mongoose'),
    Schema = mongoose.Schema;

    var transitionProbabilitySchema;
    transitionProbabilitySchema = new Schema({
       _id: {
           from_node_id: {type: Schema.Types.ObjectId, ref: "Zone"}
       },
       value: {
           total_transition_count: Number,
           probabilities: [
               {to_node_id: {type: Schema.Types.ObjectId, ref: "Zone"}},
               {probability: Number}
           ]}
    }, {collection: 'transitionProbability'});

    module.exports = mongoose.model('transitionProbability', transitionProbabilitySchema);

and when I now call

    TransitionProbability.findOne({"_id.from_node_id": from_node_id},
            function (err, tp) {
                if (err) {
                    handleError('error - tp not found', err, callback);
                } else {
                     // some modification of tp and then save
                }
            }

Mongoose returns the document, but only `_id`is not initialized. The whole function crashes when I am trying to save the altered document and not before. I also logged the document to the console to verify it is just the `_id' field missing.

PS: note, that the `from_node_id` is extracted from another query and is a valid `ObjectId`.

**Comment by vkarpov15** [comment]
So this is also fixed in 4.0.0-rc1, the below standalone script:

```javascript
var mongoose = require('mongoose');
var Schema = mongoose.Schema;

mongoose.connect('mongodb://localhost:27017/gh-2646');

var transitionProbabilitySchema;
transitionProbabilitySchema = new Schema({
   _id: {
       from_node_id: {type: Schema.Types.ObjectId, ref: "Zone"}
   },
   value: {
       total_transition_count: Number,
       probabilities: [
           {to_node_id: {type: Schema.Types.ObjectId, ref: "Zone"}},
           {probability: Number}
       ]}
}, {collection: 'transitionProbability'});

var Model = mongoose.model('transitionProbability', transitionProbabilitySchema);

Model.remove({}, function() {
  var t = new Model({ _id: { from_node_id: '000000000000000000000001' } });
  console.log(JSON.stringify(t));
  t.save(function(err, t2) {
    console.log(err + ' :: ' + JSON.stringify(t2));
    Model.findOne({ '_id.from_node_id': t2._id.from_node_id }, function(err, t3) {
      console.log(err + ' :: ' + JSON.stringify(t3));
      t3.save(function(err) {
        console.log(err);
      });
    });
  });
});
```

Gives me the expected output when run with 4.0.0-rc1. I get the cast error with 3.8.22 though. I'll work on backporting a fix for 3.8.x, but if you want a speedy fix I'd recommend you use v4.0.0-rc1.

**Comment by Zonic** [comment]
Thanks, for your help. I can not reproduce my error in the v4.0.0-rc1 anymore. Could you may send me a message when the v4 is going to be released in stable?

**Comment by vkarpov15** [comment]
I'll make announcements on [google groups](https://groups.google.com/forum/#!forum/mongoose-orm) and [twitter](https://twitter.com/mongoosejs) when 4.0.0 is stable :)

**Comment by Lenowar** [comment]
I have this error too, but when I install 4.0, i get this error: 

--
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Console.debug.register.messageId [as trace] (eval at WRAPPED_BY_NODE_INSPECTOR (C:\Users\Leandro Hoffmann\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
\v8-debug.js:95:15), <anonymous>:123:19)
    at addListener (events.js:160:15)
    at Server.connect (C:\Dev\oaj\node_modules\mongoose\node_modules\mongodb\lib\server.js:291:17)
    at Db.open (C:\Dev\oaj\node_modules\mongoose\node_modules\mongodb\lib\db.js:190:19)
    at MongoStore.module.exports._open_database (C:\Dev\oaj\node_modules\connect-mongo\lib\connect-mongo.js:182:15)
    at MongoStore.module.exports._get_collection (C:\Dev\oaj\node_modules\connect-mongo\lib\connect-mongo.js:177:14)
    at module.exports._open_database (C:\Dev\oaj\node_modules\connect-mongo\lib\connect-mongo.js:194:16)
    at Db.open (C:\Dev\oaj\node_modules\mongoose\node_modules\mongodb\lib\db.js:200:5)
    at Server.connect.connectHandler (C:\Dev\oaj\node_modules\mongoose\node_modules\mongodb\lib\server.js:272:7)
    at g (events.js:180:16)
(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Console.debug.register.messageId [as trace] (eval at WRAPPED_BY_NODE_INSPECTOR (C:\Users\Leandro Hoffmann\AppData\Roaming\npm\node_modules\node-inspector\node_modules\v8-debug
\v8-debug.js:95:15), <anonymous>:123:19)
    at addListener (events.js:160:15)
    at once (events.js:185:8)
    at Server.connect.connectHandler (C:\Dev\oaj\node_modules\mongoose\node_modules\mongodb\lib\server.js:265:19)
    at g (events.js:180:16)
    at emit (events.js:95:17)
    at connectHandler (C:\Dev\oaj\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:373:23)
    at Server.command (C:\Dev\oaj\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:770:13)
    at Callbacks.emit (C:\Dev\oaj\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:84:3)
    at messageHandler (C:\Dev\oaj\node_modules\mongoose\node_modules\mongodb\node_modules\mongodb-core\lib\topologies\server.js:218:23)

**Comment by vkarpov15** [comment]
That's an issue with connect-mongo. @whitecolor would know better than me how to fix it. Alternative solution is to use [connect-mongodb-session](https://www.npmjs.com/package/connect-mongodb-session), which is intended to be a more durable replacement for connect-mongo.

**Comment by Lenowar** [comment]
Error: Most middleware (like session) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.forEach.Object.defineProperty.get (C:\Dev\oaj\node_modules\express\lib\express.js:89:13)
    at module.exports (C:\Dev\oaj\node_modules\connect-mongodb-session\index.js:5:39)
    at Object.<anonymous> (C:\Dev\oaj\config\express.js:18:20)

See my class here: http://pastebin.com/dyjvNf0J

**Comment by Lenowar** [comment]
I resolved the comment above and I using your library, but the session its not saved on mongo, see my last changed class:

http://pastebin.com/mC02wdfa

**Comment by vkarpov15** [comment]
I opened up an issue in connect-mongodb-session to track that, that's not a mongoose issue.

**Comment by midthun** [comment]
I get this error as well after updating to Mongoose 4.0.4. The error is: 

{ [CastError: Cast to number failed for value "[object Object]" at path "_id"]
  message: 'Cast to number failed for value "[object Object]" at path "_id"',
  name: 'CastError',
  kind: 'number',
  value: 
   { _id: 556e186f6b0b77675c3d9075,
     date: Tue Jun 02 2015 22:56:15 GMT+0200 (CEST) },
  path: '_id' }

Schema: 
...
searches: [{ 
    date: { 
      type: Date, required: false, 'default': Date.now 
    }, 
    _id: {
      type: mongoose.Schema.Types.ObjectId, ref: 'Search' 
    }
  }]
...

both _id is definitely an ObjectId, but I still get this error. I now get this error even if I downgrade back to 3.8. Also tried removing the collections and re-create them. 

Also, if I do a findOne on the schema, the _id field is missing on the "searches", but I can clearly see that they are there in Robomongo or similar.

**Comment by vkarpov15** [comment]
@midthun can you open up a separate issue and show me how you're getting the document that triggers this cast error? Is this happening if you `find()` and then `save()` or are you creating a new document?

**Comment by midthun** [comment]
Sure, opened a new issue here: https://github.com/Automattic/mongoose/issues/3048
