### ISSUE TITLE
Trying to open unclosed connection issue in v4.0.0-rc1

### ISSUE THREAD

**Issue by mattma** [LearnBoost/mongoose#2658]
I have a working solution with the combination of `mongoose` and `express.js`. Now, I am refactoring my app from `express.js` to `koa.js`. To take advantage of `Promise`, so that I am using the latest `v4.0.0-rc1`.

```js
function bootstrap (opts) {
  return new Promise(function (resolve, reject) {
    mongoose.connect(opts.dbURI);
   
    // setup all schema
    var schemasCollection = require('./schemas')(mongoose);
    /// setup all model, based on predefined schema
    var modelCollection = require('./models')(mongoose, schemasCollection);

    resolve(myModelCollection);
  });
}

function db (opts) {
  opts = opts || {};

  return function *connectDb (next) {
    this.state.models = yield bootstrap(opts);
    yield next;
  }
}

module.exports = db;
```

So in my `router` file, I could successfully query the db, and get the results. 

```js
function getByUsername () {
  return function *getByUsername (next) {
    var username = this.params.username;
    // User is the User collection, the model
    this.body = yield User.findOne({username: username}).exec();
  }
}

router.get('/users/:username', getByUsername());
```

Here is the problem. When I query the first time, it works fine. It returns the object which contains the requested user, Then, I use the same query to query the db again, I got the error. 

```bash
  <-- GET /api/users/validuser
  xxx GET /api/users/validuser 500 2ms -

  Error: Trying to open unclosed connection.
      at NativeConnection.Connection.open (/node_modules/mongoose/lib/connection.js:220:15)
      at Mongoose.connect (node_modules/mongoose/lib/index.js:247:15)
      at server/db/index.js:26:14
      at tryCatcher (node_modules/bluebird/js/main/util.js:24:31)
      at Promise._resolveFromResolver (node_modules/bluebird/js/main/promise.js:456:31)
      at new Promise (node_modules/bluebird/js/main/promise.js:54:37)
      at bootstrap (/Users/qma17/Desktop/repos/default/ts/server/db/index.js:15:10)
      at Object.connectDb (server/db/index.js:39:31)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (node_modules/koa/node_modules/co/index.js:59:19)
      at node_modules/koa/node_modules/co/index.js:48:5
      at Object.co node_modules/koa/node_modules/co/index.js:47:10)
      at Object.toPromise node_modules/koa/node_modules/co/index.js:112:63)
      at next node_modules/koa/node_modules/co/index.js:93:29)
      at onFulfilled node_modules/koa/node_modules/co/index.js:63:7)
      at node_modules/koa/node_modules/co/index.js:48:5
```

Is this something that I did wrong? The exactly same code works in Express.js case. But not in Koa.js. I knew that I need to handle `generator`, It is very simple code for testing purpose. Is it a bug in ` v4.0.0-rc1` ?

**Comment by vkarpov15** [comment]
@mattma it looks like you're calling `bootstrap()` every time somebody hits the /api/users/validuser route? That will cause the error you're seeing: you should only call `mongoose.connect()` once

**Comment by mattma** [comment]
@vkarpov15 You are a life saver. It is definitely a user error. I have fixed it and it works fine.
