### ISSUE TITLE
MongoError: cursor killed or timed out, I don't understand...

### ISSUE THREAD

**Issue by menems** [LearnBoost/mongoose#2667]
Hi

A little sample:

```javascript
    var db = mongoose.connection;
    var strc = '...';
    db.once('open', function() {

         //init Schema
         ....
         var MODEL = mongoose.model('MODEL');

         MODEL.find({}, function(err, data) {
                if ( err) console.log(err);
                console.log('ok');
         });
    });
    mongoose.connect(strc);
```

When I run this  code on a collection of 2000 records(Schema with maybe 30 attributes) I get this error:

```
{ [MongoError: cursor killed or timed out] name: 'MongoError' }
````

db.serverStatus().metrics.cursors 

```
{
	"timedOut" : NumberLong(0),
	"open" : {
		"noTimeout" : NumberLong(0),
		"pinned" : NumberLong(0),
		"total" : NumberLong(0)
	}
}
```
edit : I try with option timeout:false, I have the same result

When I run with the native driver,  MODEL.collection.find(...toArray() I don't have this error

Is there something I miss?

mongodb version 2.6.7
mongoose version : 3.8.23

**Comment by vkarpov15** [comment]
What does your call look like when you specify the timeout option?

**Comment by menems** [comment]
I Use 
``` javascript
MODEL.find({}, {}, {timeout:false}, function(err, data){
...
}
```
thanks

**Comment by menems** [comment]
this is a code working with the mongodb driver:
``` javascript
var MongoClient = require('mongodb').MongoClient;


MongoClient.connect("mongodb://localhost:27017/db", function(err, db) {
  if(err) throw err;

    db.collection('users', function(err, collection){
        if (err) throw err;

        var count = 0;
        collection.find().each(function(err, data){
            if (err) {
                console.log(count);
                throw err;
            }
            count++;
            console.log(data.user , count);
        
        });
    });
});
```
Result is ok with count of 1361 users

The same with 'native' from mongoose:
```
// connect, schema etc.
Model.collection.find({}, function(err, cursor){

    if (err) throw err;

    cursor.count(function(err, data){
        if (err) throw err;
        console.log(data); // working as expeted -> 1361
    });

    var count = 0;
    cursor.each(function(err, data){
        if (err) {
            console.log(count);
            throw err; // stopped at 101 result with exception
        };
        count++;
        console.log(data.user);

    });
    
});

```

```
101

/Users/blaz/src/node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;      
              ^
MongoError: cursor killed or timed out
    at Object.toError (/Users/blaz/src/node_modules/mongodb/lib/mongodb/utils.js:114:11)
    at /Users/blaz/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/cursor.js:827:31
    at /Users/blaz/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/db.js:1882:9
    at Server.Base._callHandler (/Users/blaz/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
    at /Users/blaz/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
    at MongoReply.parseBody (/Users/blaz/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
    at null.<anonymous> (/Users/blaz/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
    at emit (events.js:95:17)
    at null.<anonymous> (/Users/blaz/src/node_modules/mongoose/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:201:13)
    at emit (events.js:98:17)

```

I thought about a big schema, so a i remove all subdocuments, same error.
I thought about a bad record (seeing the 101 as result )  so a i remove multiple record( with order etc.), always the same result

It 's a big issue for our company, We using a lot of cli script for sanityze an old database. And we'd like to use mongoose methods to avoid multiplication of script

Hope those samples will help

**Comment by vkarpov15** [comment]
The following script

```javascript
var mongoose = require('mongoose');
var Schema = mongoose.Schema;
var db = mongoose.createConnection('mongodb://localhost/gh2667');

var s = new Schema({
  user: String
});

var Model = db.model('gh2667', s, 'gh2667');

Model.collection.find({}, function(err, cursor){

    if (err) throw err;

    cursor.count(function(err, data){
        if (err) throw err;
        console.log(data); // working as expeted -> 1361
    });

    var count = 0;
    cursor.each(function(err, data){
        if (err) {
            console.log(count);
            throw err; // stopped at 101 result with exception
        }
        if (!data) {
          console.log('No data!');
          return;
        }
        count++;
        console.log(count);
        //console.log(data.user);

    });

});
```

Works fine for me with mongoose 4.0.0 and 3.8.23, no exceptions thrown. Can you check if the above script works in your environment?

**Comment by menems** [comment]
Hi, I tried your script and  a similar one with my Schema and empty db, no exceptions thrown ...

I have this problem only with this collection, all other working, 
For a little history, the Schema of this one is particulary big, and this collection wasn't populated from mongoose, but with the native driver with a lot of types  mistakes, I 'm going to remove property by property to see where is the problem

**Comment by menems** [comment]
I found the problem

On my user collection  I added an unique index on the Schema(user field) , But on the old db the user field is not unique ... :(

**Comment by AndreiBarsan** [comment]
For what it's worth, this exact situation also triggers the following error when encountered by the driver while running an aggregation pipeline: `exception: collection or index disappeared when cursor yielded`.
